import React from 'react';
import { cn } from '@/lib/utils';

interface OptimizedImageProps {
  /** Source PNG/JPG path, e.g. "/images/kayak.png". Resized WebP + JPG variants
   *  (-400w/-800w/-1200w) are generated by scripts/gen-images.mjs. */
  src: string;
  alt: string;
  className?: string;
  imgClassName?: string;
  sizes?: string;
  priority?: boolean;
  style?: React.CSSProperties;
}

const stripExt = (p: string) => p.substring(0, p.lastIndexOf('.')) || p;

const OptimizedImage: React.FC<OptimizedImageProps> = ({
  src,
  alt,
  className,
  imgClassName,
  sizes = '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw',
  priority = false,
  style,
}) => {
  const base = stripExt(src);
  const webpSrcSet = `${base}-400w.webp 400w, ${base}-800w.webp 800w, ${base}-1200w.webp 1200w`;
  const jpgFallback = `${base}-1200w.jpg`;

  return (
    <picture className={className}>
      <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
      <img
        src={jpgFallback}
        alt={alt}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        {...(priority ? { fetchpriority: 'high' } : {})}
        className={cn(imgClassName)}
        style={{ display: 'block', width: '100%', height: '100%', objectFit: 'cover', ...style }}
      />
    </picture>
  );
};

export default OptimizedImage;
